#!/bin/sh

rm -f /var/luci-indexcache* 2>/dev/null || true
rm -f /tmp/luci-indexcache* 2>/dev/null || true
rm -f /tmp/luci-modulecache/* 2>/dev/null || true

[ -x /etc/init.d/rpcd ] && /etc/init.d/rpcd reload || true
logger -t sheepfold "uci-defaults script executed"

exit 0
